version: "3.11"

services:
  db:
    image: postgres:15
    container_name: django_postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
  backend:
    container_name: django_backend
    build: .
    command: bash -c 'python /Django-respect/manage.py migrate && python /Django-respect/manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/usr/src/Django-respect
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    depends_on:
      - db