# Generated by Django 3.2.13 on 2023-03-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_alter_products_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
