# Generated by Django 3.2.13 on 2023-03-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20230305_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
