# Generated by Django 3.2.13 on 2023-03-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_auto_20230305_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Category',
        ),
    ]
