# Generated by Django 3.2.13 on 2023-03-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0015_auto_20230306_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
