# Generated by Django 3.2.13 on 2023-03-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20230303_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='products',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='snippets.product'),
            preserve_default=False,
        ),
    ]
