# Generated by Django 3.2.13 on 2023-03-05 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_products_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='snippets.product'),
        ),
    ]
