# Generated by Django 3.2.13 on 2023-03-06 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0013_auto_20230306_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='snippets.cart'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='snippets.product'),
            preserve_default=False,
        ),
    ]
