# Generated by Django 3.2.13 on 2023-03-17 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_rename_product_order_products'),
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='cart.cart')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='order.order')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
